version: "3"
services:
    node-app:
        # Common Configuration between dev and prod
        build: .
        ports: 
            - "3000:4000"
        env_file:
            - ./.env
        depends_on: 
            - mongo
    mongo:
        image: mongo
        volumes: 
            - mongo-db:/data/db
volumes: # Declare the volume
    mongo-db: