version: "3"
services: 
    node-app:
        volumes: 
            - ./:/app
            - /app/node_modules
        environment: 
            - NODE_ENV=development
            - MONGO_USER=othy
            - MONGO_PWD=pass
        command: npm run dev
    mongo:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=othy
            - MONGO_INITDB_ROOT_PASSWORD=pass
